title: "Warehouse Manifesto"
description: "Independent electronic music label. Techno and electro. Vinyl focused."
baseurl: "/warehousemanifesto.com"
url: "https://mechmadhog.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

permalink: /posts/:title/

defaults:
  - scope: { path: "", type: "posts" }
    values:
      layout: post
      author: "Warehouse Manifesto"
      image: ""
      featured: false
